// <auto-generated />
using System;
using ApiServices.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiServices.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240927031707_update_0")]
    partial class update_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_bin")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiServices.Models.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Details")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("FundId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CurrencyId" }, "CurrencyId");

                    b.HasIndex(new[] { "FundId" }, "FundId");

                    b.HasIndex(new[] { "UserId" }, "UserId");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("ApiServices.Models.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ValueUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique();

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("ApiServices.Models.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("LocationUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "UserId")
                        .HasDatabaseName("UserId1");

                    b.ToTable("Fund");
                });

            modelBuilder.Entity("ApiServices.Models.FundCurrency", b =>
                {
                    b.Property<Guid>("FundId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("char(36)");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.HasKey("FundId", "CurrencyId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "CurrencyId" }, "CurrencyId")
                        .HasDatabaseName("CurrencyId1");

                    b.HasIndex(new[] { "FundId" }, "FundId")
                        .HasDatabaseName("FundId1");

                    b.ToTable("Fund_Currency");
                });

            modelBuilder.Entity("ApiServices.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Role");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique()
                        .HasDatabaseName("Name1");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e89f422-615c-449e-b751-ebc85e3830d4"),
                            Name = "Asesor"
                        },
                        new
                        {
                            Id = new Guid("c373c833-29ee-48d3-b75d-113a4decbe05"),
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = new Guid("0df9f77c-9698-46e9-a17e-6974b9a13b33"),
                            Name = "Administrador"
                        });
                });

            modelBuilder.Entity("ApiServices.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("tinyblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("tinyblob");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "RoleId");

                    b.HasIndex(new[] { "Username" }, "Username")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aab43ece-fe9a-40aa-9f2c-389c690de5ea"),
                            Active = true,
                            CreatedAt = new DateTime(2024, 9, 27, 3, 17, 6, 387, DateTimeKind.Utc).AddTicks(7574),
                            Email = "admin@cewallet.org",
                            PasswordHash = new byte[] { 138, 207, 85, 42, 198, 36, 169, 249, 176, 62, 20, 64, 97, 130, 98, 45, 110, 158, 191, 243, 129, 108, 219, 102, 21, 200, 90, 81, 251, 36, 192, 152 },
                            PasswordSalt = new byte[] { 9, 161, 62, 108, 128, 20, 44, 20, 60, 239, 95, 9, 179, 253, 73, 148 },
                            RoleId = new Guid("0df9f77c-9698-46e9-a17e-6974b9a13b33"),
                            UpdatedAt = new DateTime(2024, 9, 27, 3, 17, 6, 387, DateTimeKind.Utc).AddTicks(7573),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ApiServices.Models.Fund", b =>
                {
                    b.HasOne("ApiServices.Models.User", "User")
                        .WithMany("Funds")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiServices.Models.FundCurrency", b =>
                {
                    b.HasOne("ApiServices.Models.Currency", "Currency")
                        .WithMany("FundCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fund_Currency_ibfk_2");

                    b.HasOne("ApiServices.Models.Fund", "Fund")
                        .WithMany("FundCurrencies")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fund_Currency_ibfk_1");

                    b.Navigation("Currency");

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("ApiServices.Models.User", b =>
                {
                    b.HasOne("ApiServices.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_ibfk_1");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ApiServices.Models.Currency", b =>
                {
                    b.Navigation("FundCurrencies");
                });

            modelBuilder.Entity("ApiServices.Models.Fund", b =>
                {
                    b.Navigation("FundCurrencies");
                });

            modelBuilder.Entity("ApiServices.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ApiServices.Models.User", b =>
                {
                    b.Navigation("Funds");
                });
#pragma warning restore 612, 618
        }
    }
}
